<a href="https://colab.research.google.com/github/Reet1992/Deep_learning_R/blob/main/first_scratch_NN_sesovera_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)



In [3]:
from glob import glob
#directories of normal audios
#norm_data_dir = ‘./audio-processing-files/normals/’
norm_data_dir = '/content/drive/My Drive/data/cats_dogs/train/cat/'
#'F:/sensez9/Audio_ML/data/cats_dogs/train/cat/'
norm_audio_files = glob(norm_data_dir + '*.wav')

In [4]:
#### Get Feature Vector #####

import librosa
from librosa import feature
import numpy as np
fn_list_i = [
 feature.chroma_stft,
 feature.spectral_centroid,
 feature.spectral_bandwidth,
 feature.spectral_rolloff
]


fn_list_ii = [
 feature.rmse,
 feature.zero_crossing_rate
]
def get_feature_vector(y,sr): 
    feat_vect_i = [ np.mean(funct(y,sr)) for funct in fn_list_i]
    feat_vect_ii = [ np.mean(funct(y)) for funct in fn_list_ii] 
    feature_vector = feat_vect_i + feat_vect_ii 
    return feature_vector

In [5]:
norm_audios_feat = []
for file in norm_audio_files:
    y , sr = librosa.load(file,sr=None)
    feature_vector = get_feature_vector(y, sr)
    norm_audios_feat.append(feature_vector)

/usr/local/lib/python3.6/dist-packages/librosa/core/pitch.py:145: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')


In [7]:
cat = pd.DataFrame(norm_audios_feat)

cat.head()

0            1            2            3         4         5
0  0.435584  1249.411119  1547.045811  2662.154797  0.011928  0.077963
1  0.643868   561.073612  1209.945796   980.000000  0.133142  0.014814
2  0.474373  1559.410591  1685.789216  3229.255698  0.029396  0.102841
3  0.308785  1799.700430   880.207064  2348.400298  0.062971  0.206020
4  0.556036  1781.190878  1946.743514  3924.617686  0.038478  0.095425

In [9]:
#### Testing Data For Cats 



from glob import glob
#directories of normal audios
#norm_data_dir = ‘./audio-processing-files/normals/’
norm_data_dir2 = '/content/drive/My Drive/data/cats_dogs/test/cats/'
#'F:/sensez9/Audio_ML/data/cats_dogs/train/cat/'
norm_audio_files2 = glob(norm_data_dir2 + '*.wav')


norm_audios_feat2 = []
for file in norm_audio_files2:
    y2 , sr2 = librosa.load(file,sr=None)
    feature_vector2 = get_feature_vector(y2, sr2)
    norm_audios_feat2.append(feature_vector2)
    
    
## Dataframe #####


cat_test = pd.DataFrame(norm_audios_feat2)

print(cat_test.shape)
cat_test.head()

/usr/local/lib/python3.6/dist-packages/librosa/core/pitch.py:145: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')


(39, 6)


0            1            2            3         4         5
0  0.248067  1220.040390  1275.208919  2151.160714  0.139273  0.082160
1  0.488276  1345.576377   952.893098  2131.422375  0.082471  0.162979
2  0.352229   984.929517  1199.405032  1602.590461  0.188242  0.062256
3  0.477130  1788.771828  1788.250534  3604.687500  0.140053  0.112830
4  0.400303  2025.188446  1963.884878  4279.570998  0.016492  0.129101

In [10]:
### Y train Data Generate #### 

import random
randomlist2 = []
for i in range(0,125):
    n = random.randint(0,1)
    randomlist2.append(n)
print(randomlist2)

Y_train = pd.DataFrame(randomlist2)

print(Y_train.shape)

print(Y_train.head())

#### Y test Data Generate #### 

import random
randomlist = []
for i in range(0,39):
    n = random.randint(0,1)
    randomlist.append(n)
print(randomlist)

Y_test = pd.DataFrame(randomlist)

print(Y_test.shape)

print(Y_test.head())

[0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1]
(125, 1)
   0
0  0
1  0
2  1
3  1
4  0
[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0]
(39, 1)
   0
0  1
1  1
2  0
3  1
4  1


Input of X and Y

In [11]:
#X_train = cat.values
#Y_train = Y_train.values

##X_test = cat_test.values
#Y_test = Y_test.values

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(125, 6)
(125, 1)
(39, 6)
(39, 1)


**Neural Network With Back Propagation and Update Parameters :**

In [236]:
def neural_network(w,b,m):
  for i in range(0,1040):
    w, b = initialize_with_zeros(X_train.shape[0])
    m = X.shape[1]

    ### forward Propagation

    A_sig = sigmoid(np.dot(w.T, X_train) + b)
    cost_sig =  (-1 / m) * np.sum(Y_train*np.log(A_sig)+(1-Y_train)*np.log(1-A_sig))
    cost_sig =  cost_sig - 0.25 * i
    print("SigmoiD cost Function", cost_sig)

    ### Back_propagation 

    dw = (1 / m) * np.dot(X_train, (A_sig - Y_train).transpose())/400
    db = (1 / m) * np.sum(A_sig - Y_train)/400

    #### Update Parameter
    learning_rate = 0.025

    w = w + learning_rate * dw  # need to broadcast
    b = b + learning_rate * db
   #print(w,b)

  #### Y_prediction_test #### 

    m2 = X_test.shape[1]
    Y_prediction_test = np.zeros((1, m2))


    for i in range(A_sig.shape[1]):
      Y_prediction_test[0, i] = 1 if A_sig[0, i] >= 0.5 else 0
      print(Y_prediction_test)

     #### Y_prediction_train #### 

      m = X_train.shape[1]
      Y_prediction_train = np.zeros((1, m))


    for i in range(A_sig.shape[1]):
      Y_prediction_train[0, i] = 1 if A_sig[0, i] >= 0.5 else 0

      print(Y_prediction_train)


    # Print train/test Errors
  print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
  print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

  

 

In [237]:
neural_network(w,b,m)

Streaming output truncated to the last 5000 lines.
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
SigmoiD cost Function 95.93019270997951
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
SigmoiD cost Function 95.68019270997951
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
SigmoiD cost Function 95.43019270997951
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 0.]]
[[1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0